_BASE_: "./Base-C2_L_R5021k_640b64_4x.yaml"
SOLVER:
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  MODEL_EMA: 0.999
DATASETS:
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)
MODEL:
  WEIGHTS: "models/baseline_R50.pth"
  ACTIVE_ONLY_GT_TEST: true
  #ACTIVE_LOSS: "cls_stage0"
  ACTIVE_GRAD_COMPARE: true
  ACTIVE_GRAD_SAVE: true
  ACTIVE_GRAD_UPDATE: "MOMENTUM0.1"
  ACTIVE_MODE: "paste_only"
  ONLY_PASTE_SUP: true
  ACTIVE_SEED: 1
  ACTIVE_FORWARD_ONCE: true
  ACTIVE_ONCE_MODE: "only_paste_-0.05"
INPUT:
  INST_POOL: true
  INST_POOL_PATH: "YOUR_DATASET_JSON_PATH"
  INST_POOL_FORMAT: "RGBA"
  USE_COPY_METHOD: "syn_copy"
  USE_INSTABOOST: false
  MASK_FORMAT: bitmask
  CP_METHOD: ['basic']
  RANDOM_ROTATE: false
  INST_POOL_SAMPLE_TYPE: "cas_random"
  TRAIN_SIZE: 640
  ACTIVE_SELECT: true
TEST:
  EVAL_PERIOD: 30000
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
  NUM_WORKERS: 8
  PREFETCH_FACTOR: 8
